<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>ME</RootNamespace>
    <AssemblyName>ME</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <DisableHardwareAcceleration>true</DisableHardwareAcceleration>
    <ApplicationIcon>hobby_working_dailyroutine_life_time_management_icon_142245.ico</ApplicationIcon>
    <Version>2.2.1.0</Version>
    <StartupObject>ME.App</StartupObject>
    <Authors>JOE</Authors>
    <SatelliteResourceLanguages>zh-Hans</SatelliteResourceLanguages>
  </PropertyGroup>

  <Target Name="CleanPublishOutput" BeforeTargets="PrepareForPublish">
    <RemoveDir Directories="$(PublishDir)" Condition="'$(PublishDir)' != '' And Exists('$(PublishDir)')" />
  </Target>

  <Target Name="TrimPublishOutput" AfterTargets="Publish">
    <RemoveDir Directories="$(PublishDir)runtimes" Condition="'$(PublishDir)' != '' And Exists('$(PublishDir)runtimes')" />
  </Target>

  <ItemGroup>
    <Content Include="hobby_working_dailyroutine_life_time_management_icon_142245.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="WPF-UI" Version="3.0.5" />
  </ItemGroup>

</Project>
